# Copyright (C) 2024 actuarysailor
# For license information, see:
# https://github.com/actuarysailor/github-action-nodejs-local-file-copy/blob/main/LICENSE
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - '📦 Dependencies'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    versioning-strategy: 'increase'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - '📦 Dependencies'
      - '🚀 CI/CD'
