# Copyright (C) 2024 actuarysailor
# For license information, see:
# https://github.com/actuarysailor/github-action-nodejs-local-file-copy/blob/main/LICENSE
extends: default

ignore: |
  node_modules/

rules:
  document-start:
    present: false
  line-length:
    ignore: |
      /.github/actions/**/*.yml
      /.github/workflows/*.yml
      /.github/settings.yml
      /action.yml
  truthy:
    ignore: |
      /.github/workflows/*.yml
