# Copyright (C) 2024 actuarysailor
# For license information, see https://github.com/actuarysailor/github-action-nodejs-local-file-copy/blob/main/LICENSE
[files]
extend-exclude = ["dist"]

[default]
extend-ignore-re = [
  "\\b[0-9A-Za-z+/]{91}(=|==)?\\b",  # baseËš64 strings
  "[0-9a-fA-F]{7,}",                 # git commit hashes and mongo ids
]
