name: 'Local File Copy'
description: |
  A NodeJS GitHub action to search for files matching a regex pattern
  and copy them to another folder, with options to retain the
  directory structure or flatten it.
author: 'actuarysailor'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  source-directory:  # id of input
    description: 'Source directory to copy files from'
    required: false
    default: './test/source'
  destination-directory:  # id of input
    description: 'Target directory to copy files to'
    required: true
    default: './test/destination'
  file-filter:  # id of input
    description: 'Regex pattern  to use in filtering files to be copied'
    required: false
    default: '[^\r\n\t\f]+'
  flatten-directories:  # id of input
    description: 'Boolean value to determine whether to retain directory tree or flatten to a single folder'
    required: false
    default: 'false'

outputs:
  copied-files:
    description: 'List of files copied and their paths'

runs:
  using: 'node20'
  main: 'dist/index.js'
