# Copyright (C) 2024 actuarysailor
# For license information, see https://github.com/actuarysailor/github-action-nodejs-local-file-copy/blob/main/LICENSE
name: 'github-action-nodejs-template'

on:
  push:

jobs:
  gha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4

      - name: Integration Testing 🤩
        id: gha
        uses: ./
        with:
          source-directory: ./tests/source
          destination-directory: ./tests/destination
          # file-filter:  # id of input
          flatten-directories: true

      - run: |
          echo "markdown: ${{ steps.gha.outputs.copied-files }} >> $GITHUB_STEP_SUMMARY"
