name: 'github-action-nodejs-template'

on:
  push:

jobs:
  gha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4

      - name: Integration Testing 🤩
        id: gha
        uses: ./
        with:
          source-directory: ./test/source
          destination-directory: ./test/destination
          # file-filter:  # id of input
          flatten-directories: true

      - run: |
          echo "markdown: ${{ steps.gha.outputs.copied-files }} >> $GITHUB_STEP_SUMMARY"
