name: 'github-action-nodejs-template'

on:
  push:

jobs:
  gha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4

      - name: Integration Testing 🤩
        id: gha
        uses: ./
        with:
          sourceDirectory: ./test/source
          destinationDirectory: ./test/destination
          # fileFilter:  # id of input
          flattenDirectories:  true

      - run: |
          echo "markdown: ${{ steps.gha.outputs.copied-files }}"
