# Copyright (C) 2024 actuarysailor
# For license information, see https://github.com/actuarysailor/github-action-nodejs-local-file-copy/blob/main/LICENSE
name: 'Lint GitHub Actions workflows'

on:
  push:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4

      - name: Download actionlint ⚙️
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.26
        shell: bash

      - name: Check workflow files 💅🏻
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
