# Copyright (C) 2024 actuarysailor
# For license information, see https://github.com/actuarysailor/github-action-nodejs-local-file-copy/blob/main/LICENSE
name: 'Typos'

on:
  push:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4
      - name: 🙊 Run code spell checker to check typos
        uses: crate-ci/typos@v1.25.0
